### ISSUE TITLE
Not work in API 19

### ISSUE THREAD

**Issue by tank777** [fishwjy/VideoCompressor#1]
it is not working in API 19.

**Comment by 18361237136** [comment]
cannot set the resolution?

**Comment by MichaelJokAr** [comment]
@tank777  for every API19 device?

**Comment by tank777** [comment]
I don't know but may be yes it is not working for API 19 device. I have tested in the Samsung device and Nexus emulator.

**Comment by zodiacvrish** [comment]
I can t play video in exoplayer 
and there is no sound in video...what is wrong please tell me
