### ISSUE TITLE
Only one video compression at one time

### ISSUE THREAD

**Issue by yudhisthira123** [fishwjy/VideoCompressor#10]
Hi, 
As I could see VideoController class is Singleton. If I want to parallel compression of multiple video. 
will it be fine if I use single instance for parallel compression?

**Comment by fishwjy** [comment]
It don't support concurrency working.

**Comment by yudhisthira123** [comment]
Do you have any plan to make it concurrent? The thing is, I found it very useful for my use case. My use case required concurrent compression.

**Comment by fishwjy** [comment]
I'm afraid it maybe impossible currently, because the solution is based on encoder hardware, and the hardware is not allowed working concurrently.

**Comment by yudhisthira123** [comment]
Thanks for clarification.
