### ISSUE TITLE
unable to generate release apk

### ISSUE THREAD

**Issue by aishik212** [fishwjy/VideoCompressor#15]
whenever i'm trying to create the release apk this problem is coming

`Program type already present: com.coremedia.iso.AbstractBoxParser$1
Message{kind=ERROR, text=Program type already present: com.coremedia.iso.AbstractBoxParser$1, sources=[Unknown source file], tool name=Optional.of(D8)}
`
this is the video compressor gradle after a lot of commenting:
```
apply plugin: "com.android.library"

android {
    compileSdkVersion 28
    //buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        //testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
}

dependencies {
/*    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testImplementation 'junit:junit:4.12'

    //implementation files('libs/aspectjrt-1.7.3.jar')*/
    implementation files('libs/isoparser-1.0.6.jar')
}
```

**Comment by ChairfaceChippendale** [comment]
Check proguard rules:
https://stackoverflow.com/questions/32635240/what-is-the-correct-proguard-definition-for-latest-mp4parser-isoparser-library

**Comment by aishik212** [comment]
> Check proguard rules:
> https://stackoverflow.com/questions/32635240/what-is-the-correct-proguard-definition-for-latest-mp4parser-isoparser-library

i switched to this library https://github.com/natario1/Transcoder to fix all the problems related to transcoding
