### ISSUE TITLE
Why was there Jni code or so library for the native method  "com.vincent.videocompressor.VideoController.convertVideoFrame"

### ISSUE THREAD

**Issue by navyifanr** [fishwjy/VideoCompressor#2]
In the `VideoController.java`, for the native method `convertVideoFrame`
```
public native static int convertVideoFrame(ByteBuffer src, ByteBuffer dest, int destFormat, int width, int height, int padding, int swap);
```
I don't find any JNI code or so library, it maybe has some bug for the API 16-17. So how to fix the bug? Can you get some ideas?

**Comment by fishwjy** [comment]
This library don't have any C/C++ code. All the feature has been done by MediaCodec + OpenGL API.
