### ISSUE TITLE
这个库支持多线程嘛，2、3个一起压

### ISSUE THREAD

**Issue by zlmkaka** [fishwjy/VideoCompressor#5]

**Comment by fishwjy** [comment]
多线程压缩同一个视频不支持，多个不同的视频不同线程压缩是可以的

**Comment by zlmkaka** [comment]
但是我看到MediaController 是一个单例，我在用多线程压多个视频的时候，比如压2个，最后都变成了第一个，应该是要修改MediaController 变成可多线程的;  我提问只是想确认下（这个源生的库）是否支持多线程，

**Comment by fishwjy** [comment]
谢谢提醒，确实有这个问题，突然想到Android的硬件编码器应该本身就没办法多线程操作，所以多线程压缩可能无法实现，如果你有新的发现，欢迎分享经验，谢谢！
