### ISSUE TITLE
Get output path of compressed video file

### ISSUE THREAD

**Issue by droidstered** [fishwjy/VideoCompressor#6]
Will _VideoController.cachedFile.getAbsolutePath()_ give me a output path of compressed video ?

**Comment by zodiacvrish** [comment]
bro did you get that path

**Comment by zodiacvrish** [comment]
please I want to get the compressed video path tooo

**Comment by fishwjy** [comment]
VideoCompress.compressVideoLow(srcPath, **destPath**, new VideoCompress.CompressListener())
The destination path is set when you call the compress function.

**Comment by zodiacvrish** [comment]
bro can I use destpath for uploading video to firebase directy

**Comment by fishwjy** [comment]
Sure it is. 
Notice: Set the destPath which you have the right to access
