### ISSUE TITLE
华为手机colorFormat问题

### ISSUE THREAD

**Issue by robinvanPersie** [fishwjy/VideoCompressor#8]
首先，在华为手机Android6.0上，一个一个压视频没有问题。

我把videoController的单例模式取消了，如果我开启线程池，同时选择3个视频，不管是3个启动线程同时压缩，还是压1个其他2个在等待队列里，就会遇到压缩失败的问题，encoder.star()抛出了异常，logcat里有很多colorFormat unkonw的warning，请问有遇到过吗？

**Comment by fishwjy** [comment]
底层调用硬件进行编解码，应该无法支持多线程( 未经多方面验证 )，多线程情况下请慎用，谢谢！
